### ISSUE TITLE
Error with 500 code appear when you try to cancel subscription

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-subscription#1]
![image](https://user-images.githubusercontent.com/6369252/29089387-86c714f2-7c95-11e7-9aa6-729fec77f192.png)

Version info: 
- Browser version: Chrome 60
- Platform version: 2.13.14
- Module version: 1.0.3

### Expected behavior
Subscription must be cancelled without errors

### Actual behavior
Subscription was cancelled, but with error with 500 code

### Steps to reproduce
Just try to cancel any subscription

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/v1.1.0
