### ISSUE TITLE
Comment Widget does not save or display comment value

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-module-subscription#10]
On the subscription detail blade, the comment widget doesn't show existing comment values or save new comment values.  No errors are thrown.

I'm using platform version 2.13.26 and subscription module 1.1.0.

@IgorisB

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/v1.1.1

**Comment by benb1n** [comment]
That worked @tatarincev  - thanks for the quick response!
