### ISSUE TITLE
Subscription status banner on details blade shows incorrect status and balance

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-module-subscription#11]
See screenshot below.  The data in the list is correct, but the subscription details in the blue banner at the top is not.  All of the orders in the subscription are marked as paid.

![image](https://user-images.githubusercontent.com/1915482/41243683-64bf1b9c-6d68-11e8-8d16-9779b08881f2.png)

Subscription module version 1.1.1
Platform version 2.13.27

@IgorisB

**Comment by tatarincev** [comment]
@benb1n Thanks for detailed problem description. The reason of this issue there is the gap between stored subscriptions which used for search and actual subscription state which evaluate on each read or update operation. 
Subscription, which you can see in the detailed blade, always the most actual, then in the search results. 

The subscription module has a special background job for update subscription states, depends on the associated with subscription objects, such as Orders and Payments. 

Do you have these settings enabled?
![image](https://user-images.githubusercontent.com/7566324/41276224-e62ce1c6-6e23-11e8-8a18-e1264272b533.png)

**Comment by benb1n** [comment]
@tatarincev Yes, those settings are the same.  I'm not too familiar with the cron expressions, but in Hangfire it appears that expression is only going to run the job once a month instead of daily.

![image](https://user-images.githubusercontent.com/1915482/41296033-92292c58-6e21-11e8-9e36-5dfb42603759.png)

I assume this is supposed to run at least daily?

I ran the job manually, and it seemed to work fine.

**Comment by tatarincev** [comment]
Yes, apparently there were wrong cron expressions. I've changed them to Hourly `0 */1 * * *` for subscriptions processing job and to daily for `0 0 */1 * *` for recurrent order creation.

**Comment by benb1n** [comment]
@tatarincev  Thanks for fixing that!  Do you know how to update the cron expressions for the existing hangfire jobs?  I don't see a way in the Hangfire backend.  It doesn't look like changing the settings in platform affect the existing Hangfire jobs.

**Comment by tatarincev** [comment]
Try to open hangfire console by this path  'admin/hangfire' and remove these jobs from sheduled jobs tab.
