### ISSUE TITLE
Count label overlap on subscription list

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-module-subscription#12]
This may be a platform UI issue rather than a subscription module issue, but on the subscriptions page the label in the list header overlaps other controls when you have more than 999 items in the list.

![image](https://user-images.githubusercontent.com/1915482/41244128-befbcfc8-6d69-11e8-9560-eaed89032c86.png)

I thought I remember seeing this on another screen, like Orders or Contacts, when there are more than 999 items, but I didn't see it when I tried to verify just now.

@IgorisB

**Comment by yecli** [comment]
[v1.1.9](https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/v1.1.9)
