### ISSUE TITLE
Audit information on renewal order not reset when order is cloned

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-module-subscription#14]
https://github.com/VirtoCommerce/vc-module-subscription/blob/3ce0df2d4ee5b901f529a13aea80e24f8c350ea9/VirtoCommerce.SubscriptionModule.Data/Services/SubscriptionBuilderImpl.cs#L221-L227

This doesn't get called and does not reset the audit info for Auditable objects.  The call to `retVal.GetFlatObjectsListWithInterface<AuditableEntity>()` returns nothing.  Renewal orders still have the same created/modified dates as the prototype.

@IgorisB

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/v1.1.2

**Comment by benb1n** [comment]
@tatarincev Thanks again for a quick response on this.  I'll pull it down soon and verify it.
