### ISSUE TITLE
An Order is generated more than once for a given Subscription Period

### ISSUE THREAD

**Issue by adamhanlin** [VirtoCommerce/vc-module-subscription#60]
Version info: 
- Platform version: all
- Module version: all

### Expected behavior
When the CreateRecurrentOrdersJob job runs, each Subscription's CurrentPeriodStart and CurrentPeriodEnd are updated to reflect the new Period, thereby preventing the next job run from creating yet another Order for the Period.

### Actual behavior
When the CreateRecurrentOrdersJob job runs, no Subscription is updated.  As a result, an Order is created every time the job runs, regardless if one has already been created for the Period.

### Steps to reproduce
1. Create a Subscription
2. Run the CreateRecurrentOrdersJob more than once in a period (e.g. daily when the Subscription's Plan is Monthly)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7619 has been created

**Comment by Vectorfield4** [comment]
Release: https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/3.12.0
@adamhanlin Thanks for your contribution! Feel free to reopen the issue if you have any questions.
